### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by HarveyPlante** [HarveyPlante/codelab-js-intro#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://valuable-hate.surge.sh) and meets the following [project](http://lansingcodelab.com/lessons/js-intro/1) criteria:
- [x] Include a  [`button`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Example) that will display a silly, but tasteful joke in an `alert` when clicked
- [x] Return no errors (warnings are OK) when the HTML is uploaded to the [W3C Markup Validation Service](http://validator.w3.org/#validate_by_upload)
- [x] Return no errors or warnings when the JavaScript is pasted into [JavaScript Lint](http://www.javascriptlint.com/online_lint.php)

**Comment by chrisvfritz** [comment]
Looking good! All the listed criteria are met, but there are a few ways this project can still be improved:

### Surge URL isn't working

The surge URL doesn't seem to go to anything. The reason is your HTML file is called `jokeButton.html` instead of `index.html`. So it's available at `http://valuable-hate.surge.sh/jokeButton.html`, but going directly to `http://valuable-hate.surge.sh` will result in a missing page error.

### Simplified JavaScript

We're just barely scratching the surface with JavaScript in this lesson, but your JavaScript code can actually be simplified to just:

``` js
document.getElementById('btn').onclick = function() {
  alert("Because it turns \"ice\" into \"mice\"!")
};
```

In the example you're referencing in the lesson `this.src` is referring to the `src` attribute on the `img` element, which we don't need to change in this case. And we added the current date and time to the end of it, so that the browser would recognize that we needed to fetch a new image. For the joke button, none of that is necessary. 😃 

### Improving indentation

The indentation in this project is mostly good, but a little off in a few places. One easy way to fix it and see what was missing is to highlight everything with `Cmd`+`A` on a Mac or `Ctrl`+`A` on Windows, then in Atom's menu, select `Edit` > `Lines` > `Auto Indent`. A few significant advantages to consistent indentation is it's much easier for you and I to read and spot bugs.

**Comment by HarveyPlante** [comment]
**Fixed Issues**:
- Surge URL
- Simplified JavaScript
- Improved indentation

new URL -- heartbreaking-paper.surge.sh

### Thanks for the quick and descriptive feedback !

**Comment by chrisvfritz** [comment]
Terrific!! 🚀 🎆 :shipit:
